### ISSUE TITLE
Add pairtools flavor of pairs file format to import function

### ISSUE THREAD

**Issue by peterch405** [js2264/HiCExperiment#3]
Pairtools have added columns that breaks the current import function that confuses it as the 4DN format and imports the pair_type column in as frag1. https://pairtools.readthedocs.io/en/latest/formats.html#pairtools-flavor-of-pairs

**Comment by js2264** [comment]
@peterch405 thanks for pointing this out, should be fixed in https://github.com/js2264/HiCExperiment/commit/3807f49a58d9e060d63d3c8940115a498d12b82d. 
You can install this update from github: `devtools::install_github("js2264/HiCExperiment)"`
