### ISSUE TITLE
What does the balanced means in the interactions() output?

### ISSUE THREAD

**Issue by Codezy99** [js2264/HiCExperiment#9]
Hi,

Thanks for the nice pacakge : ) Could you tell me what does the balanced column means in the output of `interactions(hic)` and also random. Thanks in advance.

Best regards,
You

**Comment by js2264** [comment]
The `balanced` column refers to normalized contact counts. This normalization is typically done by `cooler`, `juicer` or `HiCPro`. You can read the papers presenting these softwares to get more insights.
